server:
  port: 4446

spring:
  activemq:
    broker-url: tcp://localhost:61616/
    user: admin
    password: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trade_accounting_audit
    username: postgres
    password: root

    initialization-mode: always

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        highlight_sql: true
        jdbc:
          timezone: UTC
  flyway:
    enabled: true
