CREATE TABLE audit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    date        TIMESTAMP WITHOUT TIME ZONE,
    employee_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_audit PRIMARY KEY (id)
);