CREATE TABLE audit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    date        TIMESTAMP WITHOUT TIME ZONE,
    employee_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_audit PRIMARY KEY (id)
);

CREATE TABLE employee
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name         VARCHAR(255),
    first_name        VARCHAR(255),
    middle_name       VARCHAR(255),
    email             VARCHAR(255),
    department_dto_id BIGINT,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

ALTER TABLE audit
    ADD CONSTRAINT FK_AUDIT_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);