TRUNCATE acceptance_productions, acceptances, acceptances_acceptance_production, access_parameters, addresses,
    agent_reports, attribute_of_calculation_objects, balance_adjustments, bank_accounts, cities, companies,
    companies_bank_accounts, contacts, contractor_groups, contractor_statuses, contractors, contractors_bank_accounts,
    contractors_contact, contracts, correction_products, corrections, corrections_correction_products,currency,
    departments,districts, employees, employees_roles, fias_db, images, internal_order,
    internal_order_internal_order_products, internal_order_products, inventarization_products, inventarizations,
    inventarizations_inventarization_products, invoice, invoice_product, legal_details, loss, loss_loss_products,
    loss_products, movement, movement_movement_products, movement_products, payments, payouts, positions, price_lists,
    product_groups, product_prises, productions, products, products_images, products_product_prices, projects,
    purchase_control, purchase_current_balance, purchase_forecast, purchase_history_of_sales, regions, remains,
    requsts_productions, retail_stores, retail_stores_cashiers, return_suppliers, roles, streets, supplier_accounts,
    task, task_comment, task_task_comments, tax_systems, technical_card_groups, technical_card_productions,
    technical_cards, technical_cards_final_production, technical_cards_materials, technical_operations,
    type_of_contractors, type_of_prices, units, warehouses, mutual_settlements, retail_sales;