create table if not exists discount
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active        BOOLEAN,
    name             VARCHAR(255)                            NOT NULL,
    type             VARCHAR(255)                            NOT NULL,
    is_bonus_program BOOLEAN,
    bonus_program_id BIGINT,
    CONSTRAINT pk_discount PRIMARY KEY (id)
);

ALTER TABLE discount
    ADD CONSTRAINT FK_DISCOUNT_ON_BONUS_PROGRAM FOREIGN KEY (bonus_program_id) REFERENCES bonus_program (id);

insert into discount (id, is_active, name, type, is_bonus_program, bonus_program_id)
values (1, true, 'Бонусная программа 1', 'Бонусная программа', true, 1),
       (2, true, 'Бонусная программа 2', 'Бонусная программа', true, 2),
       (3, true, 'Бонусная программа 3', 'Бонусная программа', true, 3),
       (4, true, 'Бонусная программа 4', 'Бонусная программа', true, 4),
       (5, true, 'Бонусная программа 5', 'Бонусная программа', true, 5);